### ISSUE TITLE
Error when building with Jekyll

### ISSUE THREAD

**Issue by JonathanLindsey** [mshafer1/frclabviewtutorials#11]
When I try to run `jekyll -v` outside the frclabviewtutorials repository my output is
```
C:\Users\Jonathan\Desktop\2019\CSA>jekyll -v
jekyll 4.0.0

C:\Users\Jonathan\Desktop\2019\CSA>
```
But when I run jekyll -v inside the frclabviewtutorials repository I get
```
C:\Users\Jonathan\Desktop\2019\CSA\frclabviewtutorials>jekyll -v
Traceback (most recent call last):
        10: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
         9: from C:/Ruby26-x64/bin/jekyll:23:in `load'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler.rb:149:in `setup'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/runtime.rb:26:in `setup'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/runtime.rb:26:in `map'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/spec_set.rb:147:in `each'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/spec_set.rb:147:in `each'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/runtime.rb:31:in `block in setup'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/lib/bundler/runtime.rb:312:in `check_for_activated_spec!': You have already activated i18n 1.7.0, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

C:\Users\Jonathan\Desktop\2019\CSA\frclabviewtutorials>
```

As the last line suggested if I run `bundle exec jekyll -v` it works. However, it shows a different version. 🤥 
```
C:\Users\Jonathan\Desktop\2019\CSA\frclabviewtutorials>bundle exec jekyll -v
jekyll 3.8.6

C:\Users\Jonathan\Desktop\2019\CSA\frclabviewtutorials>
```

How should I fix my environment?

@mshafer1 in PR#6 you mentioned to run `bundle install`. That command is not in the "Building Locally" guide in the Wiki. What does it do and should it be in the wiki? Does it install dependencies that some file in the repository says are needed? If so, what is that file?

Once I understand this, I think I'll be able to update the documentation accordingly.

**Comment by mshafer1** [comment]
I think in the last couple of months, that jekyll and related have gone through some updates. It is my understanding that it is best (at this time) to launch via `bundle exec jekyll serve` - if you run that command does it work for you?

**Comment by JonathanLindsey** [comment]
Yes. That works for now. Thanks.

**Comment by JonathanLindsey** [comment]
I just setup the environment on a new computer and when I ran `bundle exec jekyll serve` for the first time it gave me this.
```
C:\Users\Jonathan\Downloads\frclabviewtutorials>bundle exec jekyll serve
Could not find gem 'jekyll (~> 3.8) x64-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

C:\Users\Jonathan\Downloads\frclabviewtutorials>
```
`bundle exec jekyll build` did the same thing.

I think we need to add `bundle install` to the Wiki documentation. See the bundle_install branch I created on the wiki which has my recommendation of how to properly rearrange the commands.

**Comment by mshafer1** [comment]
So, to clarify, running `bundle install` gets it working?

If so, then yes - go ahead and add that to the wiki (I can't see your branch, I'm guessing you didn't push it??)

**Comment by JonathanLindsey** [comment]
I had pushed. And it is now merged to master.
